### ISSUE TITLE
Create Account button in sign up does not work

### ISSUE THREAD

**Issue by victorsuarezis** [icreated/webstore#16]

**Comment by icreated** [comment]
Hi Victor,
thank you for your contribution.
I started to fix this issue ans things around slightly differently (countries with
FormGroup) & signup I dit the same. :)  I will commit to it soon.

Le mer. 8 déc. 2021 à 07:19, Victor Suárez ***@***.***> a
écrit :

**Comment by victorsuarezis** [comment]
Hi Sergey,
Thank you,
I've fixed here: https://github.com/victorsuarezis/webstore/commit/9c217f2d03d4ad60fbcb268cb346da1f2cf3e5ea
